#this is a Rhistory file, is not a clean script, this is to produce heatmaps per chromosome with bars
getwd()
library(ggplot2)
library(data.table)
 Tex_all <- fread("ld_TEX_1kb.hap.ld", header=T)
 Tex_all <- fread("/lustre07/scratch/egonza02/LD/POLLEN/LD_vcftools/ld_TEX_1kb.hap.ld", header=T)
head(Tex_all)
Tex_all$CHR <- gsub("Ha412HOChr","", Tex_all$CHR)
Tex_all$CHR <- as.numeric(Tex_all$CHR)
Tex_all <- fread("/lustre07/scratch/egonza02/LD/POLLEN/LD_vcftools/ld_TEX_1kb.hap.ld", header=T)
Tex_all$CHR_N <- gsub("Ha412HOChr","", Tex_all$CHR)
Tex_all$CHR_N <- as.numeric(Tex_all$CHR_N)
head(Tex_all)
Tex_all$Dist_between_SNPs <- Tex_all$POS2 - Tex_all$POS1
head(Tex_all)
Tex_CHR1 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr01")
Tex_CHR2 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr02")
Tex_CHR3 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr03")
Tex_CHR4 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr04")
Tex_CHR5 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr05")
Tex_CHR6 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr06")
Tex_CHR7 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr07")
Tex_CHR8 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr08")
Tex_CHR9 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr09")
Tex_CHR10 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr10")
Tex_CHR11 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr11")
Tex_CHR12 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr12")
Tex_CHR13 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr13")
Tex_CHR14 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr14")
Tex_CHR15 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr15")
Tex_CHR16 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr16")
Tex_CHR17 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr17")
Tex_CHR1$POS1 <- as.factor(Tex_CHR1$POS1)
head(Tex_CHR1)
head(Tex_all)
Tex_all <- na.omit(Tex_all)
Tex_CHR1 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr01")
Tex_CHR2 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr02")
Tex_CHR3 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr03")
Tex_CHR4 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr04")
Tex_CHR5 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr05")
Tex_CHR6 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr06")
Tex_CHR7 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr07")
Tex_CHR8 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr08")
Tex_CHR9 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr09")
Tex_CHR10 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr10")
Tex_CHR11 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr11")
Tex_CHR12 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr12")
Tex_CHR13 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr13")
Tex_CHR14 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr14")
Tex_CHR15 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr15")
Tex_CHR16 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr16")
Tex_CHR17 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr17")
Tex_CHR1$POS1 <- as.factor(Tex_CHR1$POS1)
colnames(Tex_all)
colnames(Tex_all) <- ("CHR", "POS1", "POS2", "N_CHR",             "R2",               "D",  "Dprime", "CHR_N", "Dist_between_SNPs")
colnames(Tex_all) <- c("CHR", "POS1", "POS2", "N_CHR",             "R2",               "D",  "Dprime", "CHR_N", "Dist_between_SNPs")
head(Tex_all)
Tex_CHR1 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr01")
Tex_CHR1$POS1 <- as.factor(Tex_CHR1$POS1)
head(Tex_CHR1)
Tex_CHR1_mean <- aggregate( R2 ~ POS1, Tex_CHR1, mean )
head(Tex_CHR1_mean)
Tex_CHR1_mean$POS1
head(Tex_CHR1)
head(Tex_CHR1_mean)
library(dplyr)
Tex_CHR1_topPOS2 <- Tex_CHR1 %>% group_by(POS1) %>% top_n(1, POS2)
head(Tex_CHR1_topPOS2)
Tex_CHR1_topPOS2 <- Tex_CHR1[Tex_CHR1[, .I[pt == max(POS2)], by=POS1]$V1]
Tex_CHR1$POS1 <- as.numeric(Tex_CHR1$POS1)
Tex_CHR1_topPOS2 <- Tex_CHR1 %>% group_by(POS1) %>% top_n(1, POS2)
head(Tex_CHR1_topPOS2)
Tex_CHR1_topPOS2 <- Tex_CHR1[Tex_CHR1[, .I[pt == max(POS2)], by=POS1]$V1]
Tex_CHR1_topPOS2 <- Tex_CHR1[Tex_CHR1[, .I[pt == max(POS2)], by=POS1]$POS1]
Tex_CHR1_topPOS2 <- Tex_CHR1 %>% group_by(POS1) %>% slice(which.max(POS2))
head(Tex_CHR1_topPOS2)
savehistory("Mean_per_1kb_text.Rhistory")
Tex_CHR1 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr01")
str(Tex_CHR1)
Tex_CHR1_topPOS2 <- Tex_CHR1 %>% group_by(POS1) %>% slice(which.max(POS2))
head(Tex_CHR1_topPOS2)
Tex_CHR1$POS1 <- as.factor(Tex_CHR1$POS1)
Tex_CHR1_topPOS2 <- Tex_CHR1 %>% group_by(POS1) %>% slice(which.max(POS2))
head(Tex_CHR1_topPOS2)
 Tex_CHR1 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr01")
Tex_CHR1_POS1_POS2 <- Tex_CHR1[,c(2,3)]
head(Tex_CHR1_POS1_POS2)
Tex_CHR1_topPOS2 <- Tex_CHR1_POS1_POS2 %>% group_by(POS1) %>% slice(which.max(POS2))
head(Tex_CHR1_topPOS2)
head(Tex_CHR1_POS1_POS2)
head(Tex_CHR1_topPOS2)
ls()
head(Tex_CHR1_mean)
nrow(Tex_CHR1_mean)
nrow(Tex_CHR1_topPOS2)
head(Tex_CHR1)
Tex_CHR1_men_maoxPOS2 <- cbind(Tex_CHR1_topPOS2, Tex_CHR1_mean)
head(Tex_CHR1_men_maoxPOS2)
Tex_CHR1_men_maoxPOS2 <- cbind.data.frame(Tex_CHR1_topPOS2, Tex_CHR1_mean)
head(Tex_CHR1_men_maoxPOS2)
tail(Tex_CHR1_men_maoxPOS2)
summary(Tex_CHR1_men_maoxPOS2$POS2 - Tex_CHR1_men_maoxPOS2$POS1)
nrow(Tex_CHR1)
nrow(Tex_CHR1_men_maoxPOS2)
savehistory("Mean_per_1kb_text.Rhistory")
Tex_CHR1_men_maoxPOS2$CHR <- "Ha412HOChr01"
head(Tex_CHR1_men_maoxPOS2)
Tex_CHR2 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr02")
Tex_CHR3 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr03")
Tex_CHR4 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr04")
Tex_CHR5 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr05")
Tex_CHR6 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr06")
Tex_CHR7 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr07")
Tex_CHR8 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr08")
Tex_CHR9 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr09")
Tex_CHR10 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr10")
Tex_CHR11 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr11")
Tex_CHR12 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr12")
Tex_CHR13 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr13")
Tex_CHR14 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr14")
Tex_CHR15 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr15")
Tex_CHR16 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr16")
Tex_CHR17 <- subset(Tex_all, Tex_all$CHR=="Ha412HOChr17")
Tex_CHR2_mean <- aggregate( R2 ~ POS1, Tex_CHR2, mean )
Tex_CHR3_mean <- aggregate( R2 ~ POS1, Tex_CHR3, mean )
Tex_CHR4_mean <- aggregate( R2 ~ POS1, Tex_CHR4, mean )
Tex_CHR5_mean <- aggregate( R2 ~ POS1, Tex_CHR5, mean )
head(Tex_CHR2_mean)
head(Tex_CHR2)
9.75515e-05
options(scipen=999)
head(Tex_CHR2)
Tex_CHR2_POS1_POS2 <- Tex_CHR2[,c(2,3)]
Tex_CHR3_POS1_POS2 <- Tex_CHR3[,c(2,3)]
Tex_CHR4_POS1_POS2 <- Tex_CHR4[,c(2,3)]
Tex_CHR5_POS1_POS2 <- Tex_CHR5[,c(2,3)]
Tex_CHR2_topPOS2 <- Tex_CHR2_POS1_POS2 %>% group_by(POS1) %>% slice(which.max(POS2))
head(Tex_CHR2_topPOS2)
head(Tex_CHR2_mean)
Tex_CHR1_men_maoxPOS2$POS1 <-  as.numeric(as.character(Tex_CHR1_men_maoxPOS2$Tex_CHR1_men_maoxPOS2$POS1 <-  as.numeric(as.character(Tex_CHR1_men_maoxPOS2$POS1))POS1))
head(Tex_CHR1_men_maoxPOS2)
Tex_CHR1_men_maoxPOS2$POS1 <-  as.numeric(as.character(Tex_CHR1_men_maoxPOS2$POS1))
head(Tex_CHR1_men_maoxPOS2)
Tex_CHR2_men_maoxPOS2 <- cbind.data.frame(Tex_CHR2_topPOS2, Tex_CHR2_mean)
Tex_CHR3_men_maoxPOS2 <- cbind.data.frame(Tex_CHR3_topPOS2, Tex_CHR3_mean)
Tex_CHR3_topPOS2 <- Tex_CHR3_POS1_POS2 %>% group_by(POS1) %>% slice(which.max(POS2))
Tex_CHR4_topPOS2 <- Tex_CHR4_POS1_POS2 %>% group_by(POS1) %>% slice(which.max(POS2))
Tex_CHR5_topPOS2 <- Tex_CHR5_POS1_POS2 %>% group_by(POS1) %>% slice(which.max(POS2))
Tex_CHR3_men_maoxPOS2 <- cbind.data.frame(Tex_CHR3_topPOS2, Tex_CHR3_mean)
Tex_CHR4_men_maoxPOS2 <- cbind.data.frame(Tex_CHR4_topPOS2, Tex_CHR4_mean)
Tex_CHR5_men_maoxPOS2 <- cbind.data.frame(Tex_CHR5_topPOS2, Tex_CHR5_mean)
head(Tex_CHR3_men_maoxPOS2)
Tex_CHR2_men_maoxPOS2$CHR <- "Ha412HOChr02"
Tex_CHR3_men_maoxPOS2$CHR <- "Ha412HOChr03"
Tex_CHR4_men_maoxPOS2$CHR <- "Ha412HOChr04"
Tex_CHR5_men_maoxPOS2$CHR <- "Ha412HOChr05"
TEX_CHR1_5_mean_maoxPOS2 <- rbind(Tex_CHR1_men_maoxPOS2, Tex_CHR2_men_maoxPOS2, Tex_CHR3_men_maoxPOS2, Tex_CHR4_men_maoxPOS2, Tex_CHR5_men_maoxPOS2)
str(Tex_CHR2_men_maoxPOS2)
head(Tex_CHR1_men_maoxPOS2)
head(Tex_CHR2_men_maoxPOS2)
str(Tex_CHR1_men_maoxPOS2)
Tex_CHR1_men_maoxPOS2[,3] <- NULL
str(Tex_CHR1_men_maoxPOS2)
Tex_CHR2_men_maoxPOS2[,3] <- NULL
Tex_CHR3_men_maoxPOS2[,3] <- NULL
Tex_CHR4_men_maoxPOS2[,3] <- NULL
Tex_CHR5_men_maoxPOS2[,3] <- NULL
TEX_CHR1_5_mean_maoxPOS2 <- rbind(Tex_CHR1_men_maoxPOS2, Tex_CHR2_men_maoxPOS2, Tex_CHR3_men_maoxPOS2, Tex_CHR4_men_maoxPOS2, Tex_CHR5_men_maoxPOS2)
head(TEX_CHR1_5_mean_maoxPOS2)
tail(TEX_CHR1_5_mean_maoxPOS2)
TEX_CHR1_5_mean_maoxPOS2$CHR_N <-gsub("Ha412HOChr","", TEX_CHR1_5_mean_maoxPOS2$CHR))
TEX_CHR1_5_mean_maoxPOS2$CHR_N <-gsub("Ha412HOChr","", TEX_CHR1_5_mean_maoxPOS2$CHR)
TEX_CHR1_5_mean_maoxPOS2$CHR_N  <- as.numeric(TEX_CHR1_5_mean_maoxPOS2$CHR_N)
head(TEX_CHR1_5_mean_maoxPOS2)
P <- ggplot(TEX_CHR1_5_mean_maoxPOS2) +    geom_rect(aes(xmin = CHR_N - 0.1,  xmax = CHR_N + 0.1, ymin = POS1,  ymax = POS2,   fill = R2))
ggsave("TEX_CHR1_5_mean_maoxPOS2.jpg", P)
ggsave("TEX_CHR1_5_mean_maoxPOS2.pdf", P)
P <- ggplot(TEX_CHR1_5_mean_maoxPOS2) +    geom_rect(aes(xmin = CHR_N - 0.1,  xmax = CHR_N + 0.1, ymin = POS1,  ymax = POS2,   fill = R2)) +   scale_y_reverse() +   scale_fill_distiller(pale
tte = "RdYlBu")
ggsave("TEX_CHR1_5_mean_maoxPOS2_blue.pdf", P)
ls()
head(Tex_CHR1)
head(Tex_CHR2)
for i in 1:17 {
for (i in 1:17) {
name <-  paste("Tex_CHR", f, sep="")
head(Tex_all)
getwd()
ls()
Cal_all <- fread("/lustre07/scratch/egonza02/LD/POLLEN/LD_vcftools/ld_CAL_1kb.hap.ld", head=T)
savehistory("Mean_per_1kb_text.Rhistory")
head(Cal_all)
colnames(Cal_all)
colnames(Cal_all) <- c("CHR",    "POS1",   "POS2",   "N_CHR",  "R2",    "D",      "Dprime")
